backend:
  name: git-gateway
  branch: main # sau numele branch-ului principal

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pagini"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "blocks"
    label: "Blocuri"
    folder: "content/blocks"
    extension: ".md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }